name: CI/CD Pipeline for Vercel

on:
  push:
    branches:
      - '**'  # Run on all branches

jobs:
  # STAGE 1: TESTING
  test:
    name: 🧪 Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install Dependencies
        run: npm ci

      - name: 🧪 Run Tests
        run: npm test

  # STAGE 2: DEPLOYMENT (only on 'prod' branch)
  deploy:
    name: 🚀 Deploy to Vercel (Production)
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/prod' && success()
    steps:
      - name: 🔗 Trigger Vercel Deploy Hook
        run: curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }}

