name: CI/CD Pipeline for Vercel

on:
  push:
    branches:
      - "**" # Run on all branches

jobs:

  # STAGE 1: TESTING
  test:
    name: 🧪 Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 💾 Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: 📦 Install Dependencies
        run: npm ci

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: 🧪 Run Tests
        run: npm test

  lint:
    name: 🧹 Run Lint Checks
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 💾 Restore node_modules from cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: 📦 Install Dependencies
        run: npm ci

      - name: 🧪 Run Lint
        run: npm run lint

  # STAGE 2: DEPLOYMENT (only on 'prod' branch)
  deploy:
    name: 🚀 Deploy to Vercel (Production)
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/prod' && success()
    steps:
      - name: 🔗 Trigger Vercel Deploy Hook
        run: curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }}

